config/routes.rb
DemoAjaxPopUp::Application.routes.draw do
  resources :pichangas
  resources :canchas

end

app/models/cancha.rb
class Cancha < ActiveRecord::Base
	belongs_to :distrito
	has_many :pichangas

    def self.search(search)
		if search
			find(:all, :conditions => ['nombre like ?',"%#{search}%"])
		else
			find(:all)
		end
	end
end

app/models/detallepichanga.rb
class Detallepichanga < ActiveRecord::Base
	belongs_to :pichanga
	belongs_to :jugador
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
	has_many :canchas
end

app/models/jugador.rb
class Jugador < ActiveRecord::Base
	has_many :pichangas
end

app/models/pichanga.rb
class Pichanga < ActiveRecord::Base
	has_many :detallepichangas
	belongs_to :jugador
	belongs_to :cancha

    def self.search(search)
		if search
			find(:all, :conditions => ['titulo like ?',"%#{search}%"])
		else
			find(:all)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/canchas_controller.rb
class CanchasController < ApplicationController
    # GET /canchas/1
    def show
	    @cancha = Cancha.find(params[:id])

	    respond_to do |format|
	      format.html # show.html.erb
	      format.json { render json: @cancha }
	    end
    end
end

app/controllers/pichangas_controller.rb
class PichangasController < ApplicationController
  # GET /pichangas
  # GET /pichangas.json
  def index
    @pichangas = Pichanga.search(params[:search])
  end

  # GET /pichangas/1
  # GET /pichangas/1.json
  def show
    @pichanga = Pichanga.find(params[:id])
    @canchas = Cancha.all
    @cancha = @pichanga.cancha

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pichanga }
    end
  end

  # GET /pichangas/new
  # GET /pichangas/new.json
  def new
    @pichanga = Pichanga.new
    @canchas = Cancha.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pichanga }
    end
  end

  # GET /pichangas/1/edit
  def edit
    if params[:search].nil?
      @pichanga = Pichanga.find(params[:id])
      @cancha = @pichanga.cancha
    end
    @canchas = Cancha.search(params[:search])
  end

  # POST /pichangas
  # POST /pichangas.json
  def create
    @pichanga = Pichanga.new(params[:pichanga])
    @canchas = Cancha.all

    respond_to do |format|
      if @pichanga.save
        format.html { redirect_to @pichanga, notice: 'Pichanga was successfully created.' }
        format.json { render json: @pichanga, status: :created, location: @pichanga }
      else
        format.html { render action: "new" }
        format.json { render json: @pichanga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pichangas/1
  # PUT /pichangas/1.json
  def update
    @pichanga = Pichanga.find(params[:id])
    @canchas = Cancha.all

    respond_to do |format|
      if @pichanga.update_attributes(params[:pichanga])
        format.html { redirect_to @pichanga, notice: 'Pichanga was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pichanga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pichangas/1
  # DELETE /pichangas/1.json
  def destroy
    @pichanga = Pichanga.find(params[:id])
    @pichanga.destroy

    respond_to do |format|
      format.html { redirect_to pichangas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cancha_helper.rb
module CanchaHelper
end

app/helpers/pichangas_helper.rb
module PichangasHelper
end

app/views/canchas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @cancha.nombre %>
</p>

<p>
  <b>Ubicaci&oacute;n:</b>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=true&zoom=16&markers=#{@cancha.latitud}%2C#{@cancha.longitud}" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoPichangas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pichangas/_form.html.erb
<%= form_for(@pichanga) do |f| %>
  <% if @pichanga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pichanga.errors.count, "error") %> prohibited this pichanga from being saved:</h2>

      <ul>
      <% @pichanga.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :nrojugadores %><br />
    <%= f.number_field :nrojugadores %>
  </div>
  <div class="field">
    <%= f.label :precio %><br />
    <%= f.text_field :precio %>
  </div>
  <div class="field">
    <%= f.label :nrohoras %><br />
    <%= f.number_field :nrohoras %>
  </div>
  <div class="field">
    <%= f.label :fechainicio %><br />
    <%= f.datetime_select :fechainicio %>
  </div>
  <div class="field">
    <%= f.label :fechafin %><br />
    <%= f.datetime_select :fechafin %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br />
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :cancha %><br />
    <%= f.text_field :cancha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pichangas/_pichanga.html.erb
<div class="pichanga">
  <h3>
    <%= link_to pichanga.titulo, pichanga %>
  </h3>
  <div class="actions">
    <%= link_to "Edit", edit_pichanga_path(pichanga) %> |
    <%= link_to "Destroy", pichanga, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>


app/views/pichangas/edit.html.erb
<h1>Editing pichanga</h1>

<%= render 'form' %>

<input type="submit" value="Press me please!" id="showCanchas" />

<div id="popupCanchas">
  <a id="popupCanchasClose">x</a> 
  <h1>Listado de canchas</h1>
  <p id="contactArea">
    <%= form_tag edit_pichanga_path, :method => :get, :remote => true do %>
      <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
    <ul id="canchas">
    </ul>
  </p>
</div>
<div id="backgroundPopup"></div> 
<br/><br/>
<%= link_to 'Show', @pichanga %> |
<%= link_to 'Back', pichangas_path %>

app/views/pichangas/edit.js.erb
$("#canchas").empty();
<% @canchas.each do |u| %>
  $("#canchas").append("<li><a href='/canchas/<%= u.id %>' target='_blank'><%= u.nombre %></a></li>");
<% end %>

app/views/pichangas/index.html.erb
<h1>Listing pichangas</h1>

<%= form_tag pichangas_path, :method => :get, :remote => true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<div id="pichangas">
  <%= render @pichangas %>
</div>
<br />
<%= link_to 'New Pichanga', new_pichanga_path %>

app/views/pichangas/index.js.erb
$("#pichangas").html("<%= escape_javascript(render(@pichangas)) %>");

app/views/pichangas/new.html.erb
<h1>New pichanga</h1>

<%= render 'form' %>

<%= link_to 'Back', pichangas_path %>

app/views/pichangas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @pichanga.titulo %>
</p>

<p>
  <b>Nrojugadores:</b>
  <%= @pichanga.nrojugadores %>
</p>

<p>
  <b>Precio:</b>
  <%= @pichanga.precio %>
</p>

<p>
  <b>Nrohoras:</b>
  <%= @pichanga.nrohoras %>
</p>

<p>
  <b>Fechainicio:</b>
  <%= @pichanga.fechainicio %>
</p>

<p>
  <b>Fechafin:</b>
  <%= @pichanga.fechafin %>
</p>

<p>
  <b>Comentario:</b>
  <%= @pichanga.comentario %>
</p>

<p>
  <b>Estado:</b>
  <%= @pichanga.estado %>
</p>


<%= link_to 'Edit', edit_pichanga_path(@pichanga) %> |
<%= link_to 'Back', pichangas_path %>